### ISSUE TITLE
uvcat crashes with a segfault

### ISSUE THREAD

**Issue by karpatx** [bodokaiser/libuv-snippets#5]
I started using libuv four days ago and I found a memory leak.
If you call uv_fs_open, it trashes the memory after the end of uv_fs_t pointer (&open_req in this case).
Have you experienced anything like that or I missing something here ?

**Comment by bodokaiser** [comment]
@karpatx you have to pass a file name as parameter on execution:

```
./cat.o cat.c
```

I should have add some if clause which checks if a file name was given but it is also a bit strange that libuv does not complain.

Bodo

**Comment by bodokaiser** [comment]
added no argument case handler 900139644176122b3e027cb061e131af7909e0d9
